### PR TITLE
:memo: add korean translation.

### PR DESCRIPTION
**Pull request by queso-gato1355**
According to #33, I added the new Korean translation for this mod. 

I firstly request this to merge to main branch, but if you want to merge it somewhere else, please let me know.

### CODE REVIEW

**Comment by queso-gato1355** [comment]
I find out that for version 1.20 there are slightly different and added ones so if that case, please use this translations.
```
  "block.ravencoffee.coffee_grinder_block": "커피 분쇄기",
  "container.ravencoffee.coffee_grinder_registry_name": "커피 분쇄기",
  "block.ravencoffee.coffee_beans_roasted_block": "커피 원두 블록",
  "block.ravencoffee.coffee_beans_roasted_magma_block": "마그마 원두 블록",
  "block.ravencoffee.coffee_leaves_block": "커피나무 잎",
  "block.ravencoffee.brownie_block": "엄청 큰 브라우니",
  "block.ravencoffee.rosca_de_reyes_block": "로스카 데 레예스",
  "block.ravencoffee.tiramisu_block": "티라미수",
  "block.ravencoffee.coffee_machine_block": "커피 머신",
  "container.ravencoffee.coffee_machine": "커피 머신",
  "block.ravencoffee.coffee_machine_premium_block": "프리미엄 커피 머신",
  "container.ravencoffee.coffee_machine_premium": "프리미엄 커피 머신",
  "block.ravencoffee.sack_block": "자루",
  "container.ravencoffee.sack": "자루",
  "block.ravencoffee.coffee_beans_magma_block": "마그마 커피 블록",
  "block.ravencoffee.coffee_tree_leaves_block": "커피나무 잎",
  "block.ravencoffee.coffee_tree_trunk_block": "커피나무 줄기",

  "entity.minecraft.villager.ravencoffee.barista": "바리스타"
```

**Comment by TheWandererRaven** [comment]
Hi! sorry for the late response, I wanted to get some things done before addressing this.
Firsto of all, thank you so much!
This looks reallly cook
Secondly, yes, I'd like you to actually take a look at the development branch and point the PR to that branch, I've been working on some general updates and the fabric version and also included the texts I'm planning on using for the 1.20+ version.

Also, please let me know how to credit you, nickname, links, etc. So I can add that where I have the relevant credits

**Comment by queso-gato1355** [comment]
You can just credit my github profile! But my profer nickname is "Adrian"!

**Comment by TheWandererRaven** [comment]
Noted, could you do this same translation for the development branch though?
whenever you have the chance of course

**Comment by queso-gato1355** [comment]
Okay! I'll try!

**Comment by TheWandererRaven** [comment]
Closing this since this was integrated in development branch in PR #36

**Pull request closed without merging**
